"""
Pydantic schemas for Agentic Advisor
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime
from enum import Enum


class AgentAction(str, Enum):
    """Possible agent actions"""
    SKIP_IRRIGATION = "SKIP_IRRIGATION"
    IRRIGATE_NOW = "IRRIGATE_NOW"
    IRRIGATE_SOON = "IRRIGATE_SOON"
    DISEASE_MONITORING = "DISEASE_MONITORING"
    DISEASE_TREATMENT = "DISEASE_TREATMENT"
    FERTILIZE = "FERTILIZE"
    HARVEST_READY = "HARVEST_READY"
    NO_ACTION = "NO_ACTION"


class AgentDecision(BaseModel):
    """Decision made by the agent"""
    farm_id: str
    action: AgentAction
    reason: str = Field(..., description="Technical reason for the decision")
    priority: str = Field(..., description="Priority level: CRITICAL, HIGH, MEDIUM, LOW")
    context: dict = Field(..., description="Farm context used for decision")
    timestamp: datetime = Field(default_factory=datetime.now)


class AgentNotification(BaseModel):
    """Notification generated by the agent"""
    farm_id: str
    action: AgentAction
    message: str = Field(..., description="Farmer-friendly message")
    priority: str
    created_at: datetime = Field(default_factory=datetime.now)


class AgentExecutionResponse(BaseModel):
    """Response from manual agent execution"""
    farm_id: str
    action: AgentAction
    reason: str
    message: Optional[str] = Field(None, description="Farmer-friendly explanation")
    notification_created: bool
    priority: str
    timestamp: datetime = Field(default_factory=datetime.now)
    
    class Config:
        json_schema_extra = {
            "example": {
                "farm_id": "farm_001",
                "action": "SKIP_IRRIGATION",
                "reason": "High rain probability and irrigation is not required",
                "message": "💧 Skip irrigation today. Rain is likely and your soil moisture is sufficient.",
                "notification_created": True,
                "priority": "HIGH",
                "timestamp": "2026-09-15T10:30:00"
            }
        }


class AgentStatusResponse(BaseModel):
    """Status response for agent"""
    farm_id: str
    has_recommendation: bool
    latest_action: Optional[AgentAction] = None
    latest_message: Optional[str] = None
    latest_timestamp: Optional[datetime] = None
    priority: Optional[str] = None
